-- Beispieldaten für die PokéCardex-Anwendung
-- Ausführen mit: wrangler d1 execute DB --local --file=migrations/sample-data.sql

-- Kartensets einfügen
INSERT INTO card_sets (set_id, name, series, printed_total, release_date, logo_url, symbol_url) VALUES ('swsh4', 'Vivid Voltage', 'Sword & Shield', 185, '2020/11/13', 'https://images.pokemontcg.io/swsh4/logo.png', 'https://images.pokemontcg.io/swsh4/symbol.png');
INSERT INTO card_sets (set_id, name, series, printed_total, release_date, logo_url, symbol_url) VALUES ('swsh3', 'Darkness Ablaze', 'Sword & Shield', 189, '2020/08/14', 'https://images.pokemontcg.io/swsh3/logo.png', 'https://images.pokemontcg.io/swsh3/symbol.png');
INSERT INTO card_sets (set_id, name, series, printed_total, release_date, logo_url, symbol_url) VALUES ('swsh2', 'Rebel Clash', 'Sword & Shield', 192, '2020/05/01', 'https://images.pokemontcg.io/swsh2/logo.png', 'https://images.pokemontcg.io/swsh2/symbol.png');

-- Pokémon-Karten einfügen
INSERT INTO pokemon_cards (card_id, name, supertype, subtypes, hp, types, evolves_from, set_id, number, rarity, image_small, image_large, tcgplayer_url, cardmarket_url) VALUES ('swsh4-1', 'Weedle', 'Pokémon', 'Basic', '50', 'Grass', NULL, 'swsh4', '1', 'Common', 'https://images.pokemontcg.io/swsh4/1.png', 'https://images.pokemontcg.io/swsh4/1_hires.png', 'https://prices.pokemontcg.io/tcgplayer/swsh4-1', 'https://prices.pokemontcg.io/cardmarket/swsh4-1');
INSERT INTO pokemon_cards (card_id, name, supertype, subtypes, hp, types, evolves_from, set_id, number, rarity, image_small, image_large, tcgplayer_url, cardmarket_url) VALUES ('swsh4-2', 'Kakuna', 'Pokémon', 'Stage 1', '80', 'Grass', 'Weedle', 'swsh4', '2', 'Uncommon', 'https://images.pokemontcg.io/swsh4/2.png', 'https://images.pokemontcg.io/swsh4/2_hires.png', 'https://prices.pokemontcg.io/tcgplayer/swsh4-2', 'https://prices.pokemontcg.io/cardmarket/swsh4-2');
INSERT INTO pokemon_cards (card_id, name, supertype, subtypes, hp, types, evolves_from, set_id, number, rarity, image_small, image_large, tcgplayer_url, cardmarket_url) VALUES ('swsh4-3', 'Beedrill', 'Pokémon', 'Stage 2', '140', 'Grass', 'Kakuna', 'swsh4', '3', 'Rare', 'https://images.pokemontcg.io/swsh4/3.png', 'https://images.pokemontcg.io/swsh4/3_hires.png', 'https://prices.pokemontcg.io/tcgplayer/swsh4-3', 'https://prices.pokemontcg.io/cardmarket/swsh4-3');
INSERT INTO pokemon_cards (card_id, name, supertype, subtypes, hp, types, evolves_from, set_id, number, rarity, image_small, image_large, tcgplayer_url, cardmarket_url) VALUES ('swsh4-4', 'Charmander', 'Pokémon', 'Basic', '70', 'Fire', NULL, 'swsh4', '4', 'Common', 'https://images.pokemontcg.io/swsh4/4.png', 'https://images.pokemontcg.io/swsh4/4_hires.png', 'https://prices.pokemontcg.io/tcgplayer/swsh4-4', 'https://prices.pokemontcg.io/cardmarket/swsh4-4');
INSERT INTO pokemon_cards (card_id, name, supertype, subtypes, hp, types, evolves_from, set_id, number, rarity, image_small, image_large, tcgplayer_url, cardmarket_url) VALUES ('swsh4-5', 'Charmeleon', 'Pokémon', 'Stage 1', '90', 'Fire', 'Charmander', 'swsh4', '5', 'Uncommon', 'https://images.pokemontcg.io/swsh4/5.png', 'https://images.pokemontcg.io/swsh4/5_hires.png', 'https://prices.pokemontcg.io/tcgplayer/swsh4-5', 'https://prices.pokemontcg.io/cardmarket/swsh4-5');
INSERT INTO pokemon_cards (card_id, name, supertype, subtypes, hp, types, evolves_from, set_id, number, rarity, image_small, image_large, tcgplayer_url, cardmarket_url) VALUES ('swsh4-6', 'Charizard', 'Pokémon', 'Stage 2', '170', 'Fire', 'Charmeleon', 'swsh4', '6', 'Rare Holo', 'https://images.pokemontcg.io/swsh4/6.png', 'https://images.pokemontcg.io/swsh4/6_hires.png', 'https://prices.pokemontcg.io/tcgplayer/swsh4-6', 'https://prices.pokemontcg.io/cardmarket/swsh4-6');
INSERT INTO pokemon_cards (card_id, name, supertype, subtypes, hp, types, evolves_from, set_id, number, rarity, image_small, image_large, tcgplayer_url, cardmarket_url) VALUES ('swsh4-7', 'Squirtle', 'Pokémon', 'Basic', '60', 'Water', NULL, 'swsh4', '7', 'Common', 'https://images.pokemontcg.io/swsh4/7.png', 'https://images.pokemontcg.io/swsh4/7_hires.png', 'https://prices.pokemontcg.io/tcgplayer/swsh4-7', 'https://prices.pokemontcg.io/cardmarket/swsh4-7');
INSERT INTO pokemon_cards (card_id, name, supertype, subtypes, hp, types, evolves_from, set_id, number, rarity, image_small, image_large, tcgplayer_url, cardmarket_url) VALUES ('swsh4-8', 'Wartortle', 'Pokémon', 'Stage 1', '90', 'Water', 'Squirtle', 'swsh4', '8', 'Uncommon', 'https://images.pokemontcg.io/swsh4/8.png', 'https://images.pokemontcg.io/swsh4/8_hires.png', 'https://prices.pokemontcg.io/tcgplayer/swsh4-8', 'https://prices.pokemontcg.io/cardmarket/swsh4-8');
INSERT INTO pokemon_cards (card_id, name, supertype, subtypes, hp, types, evolves_from, set_id, number, rarity, image_small, image_large, tcgplayer_url, cardmarket_url) VALUES ('swsh4-9', 'Blastoise', 'Pokémon', 'Stage 2', '180', 'Water', 'Wartortle', 'swsh4', '9', 'Rare Holo', 'https://images.pokemontcg.io/swsh4/9.png', 'https://images.pokemontcg.io/swsh4/9_hires.png', 'https://prices.pokemontcg.io/tcgplayer/swsh4-9', 'https://prices.pokemontcg.io/cardmarket/swsh4-9');
INSERT INTO pokemon_cards (card_id, name, supertype, subtypes, hp, types, evolves_from, set_id, number, rarity, image_small, image_large, tcgplayer_url, cardmarket_url) VALUES ('swsh4-25', 'Pikachu', 'Pokémon', 'Basic', '60', 'Lightning', NULL, 'swsh4', '25', 'Common', 'https://images.pokemontcg.io/swsh4/25.png', 'https://images.pokemontcg.io/swsh4/25_hires.png', 'https://prices.pokemontcg.io/tcgplayer/swsh4-25', 'https://prices.pokemontcg.io/cardmarket/swsh4-25');

-- Kartenpreise einfügen
INSERT INTO card_prices (card_id, platform_id, price_date, price_low, price_mid, price_high, price_market, currency) VALUES ('swsh4-6', 1, '2025-03-20', 120.5, 150.75, 200, 145.99, 'USD');
INSERT INTO card_prices (card_id, platform_id, price_date, price_low, price_mid, price_high, price_market, currency) VALUES ('swsh4-6', 2, '2025-03-20', 110, 140.5, 180, 135.75, 'EUR');
INSERT INTO card_prices (card_id, platform_id, price_date, price_low, price_mid, price_high, price_market, currency) VALUES ('swsh4-9', 1, '2025-03-20', 45.25, 60.5, 85, 55.99, 'USD');
INSERT INTO card_prices (card_id, platform_id, price_date, price_low, price_mid, price_high, price_market, currency) VALUES ('swsh4-9', 2, '2025-03-20', 40, 55.5, 75, 52.25, 'EUR');

-- Portfolio-Einträge einfügen
INSERT INTO portfolio_items (user_id, card_id, quantity, purchase_price, purchase_date, purchase_platform_id, condition, notes) VALUES ('user123', 'swsh4-6', 1, 130, '2024-12-15', 2, 'Near Mint', 'Weihnachtsgeschenk');
INSERT INTO portfolio_items (user_id, card_id, quantity, purchase_price, purchase_date, purchase_platform_id, condition, notes) VALUES ('user123', 'swsh4-9', 2, 45.5, '2025-01-10', 1, 'Excellent', 'Aus Booster Pack');
INSERT INTO portfolio_items (user_id, card_id, quantity, purchase_price, purchase_date, purchase_platform_id, condition, notes) VALUES ('user123', 'swsh4-25', 4, 0.5, '2025-02-05', 2, 'Good', 'Sammlung vervollständigen');
